- name: Add Prometheus as a Grafana data source
  uri:
    url: "http://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    body_format: json
    body:
      name: Prometheus
      type: prometheus
      access: proxy
      url: http://localhost:9090
      isDefault: true
    status_code: 200,409
